audio/urls.py
from django.urls import path

from . import views

app_name = 'audio'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:id>/edit/', views.edit, name='edit'),
    # path('<int:id>/update/', views.update, name='update'),
    # path('<int:id>/save/', views.save, name='save'),
    # path('<int:id>/delete/', views.delete, name='delete'),

    # path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('save/', views.save, name='save'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/process/', views.process, name='process'),
]

speechclassification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard'), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('grade/', include('grade.urls')),
    path('audio/', include('audio.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('tugas_2/', include('tugas_2.urls')),
    path('message/', include('message.urls')),
    path('message/', include('message.urls')),
    path('workplace_user_network/', include('workplace_user_network.urls')),
    
    path('api/', include('snippets_api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audio/models.py
from django.db import models
from django.utils import timezone

class Applicant(models.Model):
    name = models.CharField(max_length=100,default="")
    note = models.TextField(default="")

    def __str__(self):
        return self.name

class File(models.Model):
    # Applicant = models.ForeignKey(Applicant, on_delete=models.SET_NULL, null=True)
    applicant_id = models.IntegerField(default=0) # in byte
    name = models.CharField(max_length=100,default="")
    note = models.TextField(default="")
    location = models.TextField(default="")
    location_cloud = models.TextField(default="")
    size = models.IntegerField(default=0) # in byte
    duration = models.IntegerField(default=0) #in minute
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    
    def speech2text():
        return "hello transcriber output"

audio/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.conf import settings
import asyncio



from django.shortcuts import redirect
from django.core.files.storage import FileSystemStorage

from werkzeug.utils import secure_filename
from pydub import AudioSegment
import os
from google.cloud import storage

from .models import File

bucket_name = 'quantum-engine-248003.appspot.com' #pak ikhsan
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "credentials/My_First_Project-2c46ff0c115f.json" #pak ikhsan

def index(request):
    file_list = File.objects.all()
    # output = file_list
    # return HttpResponse(output)

    # template = loader.get_template('audio/index.tut.html')
    # context = {
    #     'file_list': file_list,
    # }
    # return HttpResponse(template.render(context, request))

    context = {'file_list': file_list}
    # return render(request, 'audio/index.tut.html', context)

    # context = {'audio_list': File.objects.all()}
    return render(request, 'audio/index.html', context)

class IndexView(generic.ListView):
    template_name = 'audio/index.tut.html'
    context_object_name = 'file_list'

    def get_queryset(self):
        return File.objects.all()

def edit(request, id):
    # return HttpResponse("You're looking at audio edit %s." % id)

    # try:
    #     file = File.objects.get(id=id)
    #     context = {'file': file}
    # except File.DoesNotExist:
    #     raise Http404("File does not exist")

    file = get_object_or_404(File, id=id)
    context = {'file': file}
    
    # return render(request, 'audio/detail.tut.html', context)
    return render(request, 'audio/edit.html', context)
    

def update(request, id):
    # response = "You're looking at the results of audio update %s."
    # return HttpResponse(response % id)

    file = get_object_or_404(File, id=request.POST['id'])
    # file.name = request.POST['name']
    file.note = request.POST['note']
    # file.location = request.POST['location']
    file.save()

    return HttpResponseRedirect(reverse('audio:edit', args=(file.id,)))

def save_local(request):

    if request.method == 'POST' and request.FILES['myfile']:

        myfile = request.FILES['myfile']

        file = File.objects.create()
        file.name = myfile.name
        file.location = settings.MEDIA_URL
        file.size = myfile.size
        file.save()

        # upload = UploadLocalThread()
        # upload.run(myfile)
        # UploadLocalThread.run(myfile)
        asyncio.run(UploadLocalThread.run(myfile))

    return redirect('/audio/')

import threading
# from django.core.files import UploadedFile
class UploadLocalThread(threading.Thread):
    async def run(file):
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)

def save(request):

    if request.method == 'POST' and request.FILES['myfile']:

        myfile = request.FILES['myfile']

        file = File.objects.create()
        file.name = myfile.name.split('.')[0] + ".wav"
        file.location = settings.MEDIA_URL
        file.size = myfile.size
        file.save()

        UploadCloudThread.run(myfile, file.id)

    return redirect('/audio/')

class UploadCloudThread(threading.Thread):
    def run(file, id):

        fs = FileSystemStorage()
        filename = fs.save(file.name, file)

        #jika ekstensi bukan wav, ubah jadi wav dulu
        if filename.split('.')[1] != 'wav':
            dst = filename.split('.')[0] + ".wav"
            sound = AudioSegment.from_file(os.path.join(settings.MEDIA_ROOT, filename))
            sound.export(os.path.join(settings.MEDIA_ROOT, dst), format='wav')
            os.remove(os.path.join(settings.MEDIA_ROOT, filename))
            filename = dst
        
        sound = AudioSegment.from_wav(os.path.join(settings.MEDIA_ROOT, filename))
        sound = sound.set_channels(1)
        sound = sound.set_sample_width(2)
        sound.export(os.path.join(settings.MEDIA_ROOT, filename), format='wav')

        #upload ke bucket_name yang sudah di tentukan diawal kode
        storage_client = storage.Client()
        bucket = storage_client.get_bucket(bucket_name)
        blob = bucket.blob(filename)
        blob.upload_from_filename(os.path.join(settings.MEDIA_ROOT, filename))
        blob.make_public()
        location_cloud = blob._get_download_url()

        os.remove(os.path.join(settings.MEDIA_ROOT, filename))

        file = get_object_or_404(File, id=id)
        file.location_cloud = location_cloud
        file.save()

def delete(request, id):
    file = get_object_or_404(File, id=id)
    filename = file.name
    file.delete()

    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(filename)
    blob.delete()

    return redirect('/audio/')

def process(request, id):
    return HttpResponse("You're voting on audio process %s." % id)

#mengembalikan tipe file
# def file_allowed(filename):
#     return '.' in filename and filename.rsplit('.', 1)[1].lower() in extensions

templates/audio/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form method="post" action="{% url 'audio:update' file.id %}">
                                        {% csrf_token %}

                                        <input type="hidden" id="id" name="id" value="{{ file.id }}">

                                        <!-- <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Nama Pelamar</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.Applicant }}" disabled required=""
                                                    parsley-type="email" class="form-control parsley-success"
                                                    id="inputEmail3" placeholder="Pelamar" data-parsley-id="40">
                                            </div>
                                        </div> -->

                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Nama File</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.name }}" name="name" disabled
                                                    required="" parsley-type="email"
                                                    class="form-control parsley-success" id="inputEmail3"
                                                    placeholder="Pelamar" data-parsley-id="40">
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Catatan</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.note }}" name="note"
                                                    parsley-type="email" class="form-control parsley-success"
                                                    id="inputEmail3" placeholder="" data-parsley-id="40">
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Lokasi File Local</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.location }}" name="location" disabled
                                                    required="" parsley-type="email"
                                                    class="form-control parsley-success" id="inputEmail3"
                                                    placeholder="Pelamar" data-parsley-id="40">
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                                <label for="inputEmail3" class="col-4 col-form-label">Lokasi File Cloud</label>
                                                <div class="col-7">
                                                    <input type="text" value="{{ file.location_cloud }}" name="location_cloud" disabled
                                                        required="" parsley-type="email"
                                                        class="form-control parsley-success" id="inputEmail3"
                                                        placeholder="Pelamar" data-parsley-id="40">
                                                </div>
                                            </div>

                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Ukuran File</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.size }}" name="size" disabled
                                                    required="" parsley-type="email"
                                                    class="form-control parsley-success" id="inputEmail3"
                                                    placeholder="Pelamar" data-parsley-id="40">
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Durasi File</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.duration }}" name="duration" disabled
                                                    required="" parsley-type="email"
                                                    class="form-control parsley-success" id="inputEmail3"
                                                    placeholder="Pelamar" data-parsley-id="40">
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="inputEmail3" class="col-4 col-form-label">Waktu File
                                                Dibuat</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ file.created_at }}" name="created_at"
                                                    disabled required="" parsley-type="email"
                                                    class="form-control parsley-success" id="inputEmail3"
                                                    placeholder="Pelamar" data-parsley-id="40">
                                            </div>
                                        </div>

                                        <ul class="list-inline wizard mt-3">
                                            <li class="previous list-inline-item">
                                                <a href="{% url 'audio:index' %}">
                                                    <button type="button" class="ladda-button btn btn-info"
                                                        data-style="slide-right"><i
                                                            class="mdi mdi-backspace-outline"></i> Back
                                                    </button>
                                                </a>
                                            </li>


                                            <li class="next list-inline-item">

                                                <button type="button" class="btn btn-success waves-effect waves-light"
                                                    data-toggle="modal" data-style="slide-right"
                                                    data-target=".bs-example-modal-center{{file.id}}"><i
                                                        class="mdi mdi-content-save-outline mr-1"></i> Save</button>

                                                <div class="modal fade bs-example-modal-center{{file.id}}" tabindex="-1"
                                                    role="dialog" aria-labelledby="myCenterModalLabel"
                                                    aria-hidden="true" style="display: none;">
                                                    <div class="modal-dialog modal-dialog-centered">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title" id="myCenterModalLabel">Are you
                                                                    sure
                                                                    to save?</h4>
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                    aria-hidden="true">×</button>
                                                            </div>

                                                            <div class="modal-footer">
                                                                <button type="button"
                                                                    class="btn btn-secondary waves-effect"
                                                                    data-dismiss="modal">Close</button>
                                                                    <button type="submit"
                                                                        class="btn btn-success waves-effect waves-light"
                                                                        data-style="slide-right"><i
                                                                            class="mdi mdi-delete"></i> Save</button>
                                                            </div>
                                                        </div><!-- /.modal-content -->
                                                    </div><!-- /.modal-dialog -->
                                                </div><!-- /.modal -->

                                            </li>


                                            <!-- <li class="next list-inline-item float-right">
                                                <a href="{% url 'audio:process' file.id %}">
                                                    <button type="button" class="ladda-button btn btn-danger"
                                                        data-style="slide-right"><i
                                                            class="mdi mdi-play-box-outline"></i> Process
                                                    </button>
                                                </a>
                                            </li> -->
                                        </ul>

                                    </form>
                                </div> <!-- end col -->

                            </div>
                            <!-- end row-->

                        </div> <!-- end card-body -->
                    </div> <!-- end card -->
                </div><!-- end col -->
            </div>
            <!-- end row -->

        </div> <!-- container -->

    </div> <!-- content -->

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

templates/audio/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<!-- Plugins css -->
<link href="{% static 'libs/dropzone/dropzone.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/dropify/dropify.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{% url 'audio:save' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Select audio file</label>
                                    <div class="custom-file">
                                        <input type="file" name="myfile" id="audio" multiple required>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary" value="submit">Upload</button>
                            </form>

                            <!-- <form action="{% url 'audio:save' %}" method="post" class="dropzone" id="myAwesomeDropzone">
                                {% csrf_token %}
                                <div class="fallback">
                                    <input name="file" type="file" multiple />
                                </div>

                                <div class="dz-message needsclick">
                                    <i class="h1 text-muted dripicons-cloud-upload"></i>
                                    <h3>Drop files here or click to upload.</h3>
                                </div>

                            </form>

                            <div class="clearfix text-right mt-3">
                                <form method="post" action="{% url 'audio:save' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="ladda-button btn btn-danger"
                                        data-style="slide-right"><i class="mdi mdi-send mr-1"></i>Submit
                                    </button>
                                </form>
                            </div> -->

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div><!-- end col -->
            </div>
            <!-- end row -->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">File List</h4>
                            <p></p>
                            <table id="state-saving-datatable" class="table activate-select dt-responsive nowrap">
                                <thead>
                                    <tr>
                                        <th>Upload Date</th>
                                        <!-- <th>Aplicant Name</th> -->
                                        <th>File Name</th>
                                        <th>Action</th>

                                        <!--<th>Full Text</th>-->
                                    </tr>
                                </thead>

                                <tbody>

                                    {% for file in file_list %}
                                    <tr>
                                        <!-- <td>{{ file.Applicant }}</td> -->
                                        <td>{{ file.created_at }}</td>
                                        <td>{{ file.name }}</td>
                                        <!-- <td>{{text.upload_date}}</td> -->
                                        <td>
                                            <a href="{% url 'audio:edit' file.id %}">
                                                <button type="button" class="ladda-button btn btn-success"
                                                    data-style="slide-right"><i class="mdi mdi-square-edit-outline"></i>
                                                    Edit
                                                </button>
                                            </a>

                                            <button type="button" class="btn btn-danger waves-effect waves-light"
                                                data-toggle="modal" data-target=".bs-example-modal-center{{file.id}}"><i
                                                    class="mdi mdi-delete"></i> Delete</button>

                                            <div class="modal fade bs-example-modal-center{{file.id}}" tabindex="-1"
                                                role="dialog" aria-labelledby="myCenterModalLabel" aria-hidden="true"
                                                style="display: none;">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title" id="myCenterModalLabel">Are you sure
                                                                to delete?</h4>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                aria-hidden="true">×</button>
                                                        </div>

                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary waves-effect"
                                                                data-dismiss="modal">Close</button>
                                                            <a href="{% url 'audio:delete' file.id %}">
                                                                <button type="button"
                                                                    class="btn btn-danger waves-effect waves-light"
                                                                    data-style="slide-right"><i
                                                                        class="mdi mdi-delete"></i> Delete</button>
                                                            </a>
                                                        </div>
                                                    </div><!-- /.modal-content -->
                                                </div><!-- /.modal-dialog -->
                                            </div><!-- /.modal -->


                                            <!-- <a href="{% url 'audio:process' file.id %}">
                                                <button type="button" class="ladda-button btn btn-info"
                                                    data-style="slide-right"><i class="mdi mdi-play-box-outline"></i>
                                                    Process</button>
                                            </a> -->

                                        </td>

                                        <!--<td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed neque vel massa molestie tempus at in eros. Ut sed augue ac ante bibendum efficitur ac eget lectus. In vulputate justo nec mollis gravida. Aliquam tristique tincidunt elementum. Maecenas cursus mauris sit amet rhoncus semper. Suspendisse a augue at eros eleifend consequat nec volutpat purus. Aenean viverra viverra est sed sodales. Donec porta enim quis sem lacinia, ac ullamcorper tortor sodales. Maecenas pharetra tincidunt augue non varius. Nunc euismod ut ipsum quis porta. Sed tristique eros sed urna dictum, varius ultricies nulla vehicula. In posuere lectus nec mollis ultricies. Morbi semper ligula ac nibh tempor auctor. Ut varius posuere mi, ut dapibus ipsum cursus non. Aliquam non sapien sed nulla elementum suscipit ac ut nisi.</td>-->
                                    </tr>
                                    {% endfor %}
                                    <!--<tr>
                                    <td>Mark Jurcas</td>
                                    <td>Senior Marketing Designer</td>
                                    <td>London</td>
                                    <td>43</td>
                                    <td>2012/12/18</td>
                                    <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                    <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                </tr>
                                <tr>
                                    <td>Jacob Bima</td>
                                    <td>Regional Director</td>
                                    <td>London</td>
                                    <td>19</td>
                                    <td>2010/03/17</td>
                                    <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                    <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                </tr>
                                <tr>
                                    <td>Larry the Bird</td>
                                    <td>Marketing Designer</td>
                                    <td>London</td>
                                    <td>66</td>
                                    <td>2012/11/27</td>
                                    <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                    <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                </tr>-->
                                </tbody>
                            </table>

                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div>
            <!-- end row-->

        </div> <!-- container -->

    </div> <!-- content -->

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

{% block js %}

<script src="{% static 'libs/dropzone/dropzone.min.js' %}"></script>
<script src="{% static 'libs/dropify/dropify.min.js' %}"></script>

<!-- Init js-->
<script src="{% static 'js/pages/form-fileuploads.init.js' %}"></script>

<script type="text/javascript">

    $('.custom-file input').change(function (e) {
        var files = [];
        for (var i = 0; i < $(this)[0].files.length; i++) {
            files.push($(this)[0].files[i].name);
        }
        $(this).next('.custom-file-label').html(files.join(', '));
    });

    </script>

{% endblock %}