audio/urls.py
from django.urls import path

from . import views

app_name = 'audio'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:id>/edit/', views.edit, name='edit'),
    # path('<int:id>/update/', views.update, name='update'),
    # path('<int:id>/save/', views.save, name='save'),
    # path('<int:id>/delete/', views.delete, name='delete'),

    # path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('save/', views.save, name='save'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/process/', views.process, name='process'),
]

message/urls.py
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('store/', views.store, name='store'),
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

speechclassification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard'), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('grade/', include('grade.urls')),
    path('audio/', include('audio.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('tugas_2/', include('tugas_2.urls')),
    path('message/', include('message.urls')),
    path('message/', include('message.urls')),
    path('workplace_user_network/', include('workplace_user_network.urls')),
    
    path('api/', include('snippets_api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    nim = models.IntegerField(max_length=10,default="")
    name = models.CharField(max_length=200, default="")
    word = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.word

message/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Message

# Create your views here.
def index(request):
    message = Message.objects.all()
    context = {
        'messages': message
    }

    return render(request, 'message/index.html', context)

def create(request):
    return render(request, 'message/create.html')

def store(request):
    nim = request.POST['nim']
    name = request.POST['name']
    word = request.POST['word']
    id = None
    messages = Message(id, nim,name,word)
    messages.save()

    return HttpResponseRedirect(reverse('message:index'))
    
def detail(request, id):
    message = get_object_or_404(Message, id=id)
    context = {
        'message': message
    }
     
    return render(request, 'message/detail.html', context)

def edit(request, id):
    message = get_object_or_404(Message, id=id)
    context = {
        'message': message
    }
    
    return render(request, 'message/edit.html', context)


def update(request, id):
    message = Message.objects.get(id=id)
    message.nim = request.POST['nim']
    message.name = request.POST['name']
    message.word = request.POST['word']
    message.save()

    return HttpResponseRedirect(reverse('message:index'))

def delete(request, id):
    message = get_object_or_404(Message, id=id)
    message.delete()
    
    return HttpResponseRedirect(reverse('message:index'))

templates/message/create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Create Message</h4>
                            <div class="row">
                                <div class="col-lg-12">
                                    <form method="post" action="{% url 'message:store'%}">
                                        {% csrf_token %}
                                        <div class="form-group row">
                                            <label for="inputMessage" class="col-4 col-form-label">NIM</label>
                                            <div class="col-7">
                                                <input type="text" value="" name="nim"
                                                    class="form-control parsley-success"
                                                    placeholder="Silahkan Masukan NIM" data-parsley-id="40">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputMessage" class="col-4 col-form-label">Nama</label>
                                            <div class="col-7">
                                                <input type="text" value="" name="name"
                                                    class="form-control parsley-success"
                                                    placeholder="Silahkan Masukan Nama" data-parsley-id="40">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputMessage" class="col-4 col-form-label">Pesan</label>
                                            <div class="col-7">
                                                <textarea value="" name="word" class="form-control parsley-success"
                                                    placeholder="Silahkan Masukan Pesan"
                                                    data-parsley-id="40"></textarea>
                                            </div>
                                        </div>
                                        <ul class="list-inline wizard mt-3">
                                            <li class="previous list-inline-item">
                                                <a href="{% url 'message:index' %}">
                                                    <button type="button" class="ladda-button btn btn-info"
                                                        data-style="slide-right"><i
                                                            class="mdi mdi-backspace-outline"></i> Back
                                                    </button>
                                                </a>
                                            </li>
                                            <li class="next list-inline-item">
                                                <button type="button" class="btn btn-success waves-effect waves-light"
                                                    data-toggle="modal" data-style="slide-right"
                                                    data-target=".bs-example-modal-center{{file.id}}"><i
                                                        class="mdi mdi-content-save-outline mr-1"></i> Save</button>
                                                <div class="modal fade bs-example-modal-center{{file.id}}" tabindex="-1"
                                                    role="dialog" aria-labelledby="myCenterModalLabel"
                                                    aria-hidden="true" style="display: none;">
                                                    <div class="modal-dialog modal-dialog-centered">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title" id="myCenterModalLabel">Are you
                                                                    sure
                                                                    to save?</h4>
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                    aria-hidden="true">×</button>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button"
                                                                    class="btn btn-secondary waves-effect"
                                                                    data-dismiss="modal">Close</button>
                                                                <button type="submit"
                                                                    class="btn btn-success waves-effect waves-light"
                                                                    data-style="slide-right"><i
                                                                        class="mdi mdi-content-save-outline mr-1"></i>
                                                                    Save</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </form>
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

templates/message/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Detail Message</h4>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group row">
                                        <label for="inputMessage" class="col-4 col-form-label">NIM</label>
                                        <div class="col-7">
                                            <h4 class="form-control parsley-success">{{ message.nim }}</h4>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="inputMessage" class="col-4 col-form-label">Nama</label>
                                        <div class="col-7">
                                            <h4 class="form-control parsley-success">{{ message.name }}</h4>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="inputMessage" class="col-4 col-form-label">Pesan</label>
                                        <div class="col-7">
                                            <h5>{{ message.word }}</h5>
                                        </div>
                                    </div>
                                    <ul class="list-inline wizard mt-3">
                                        <li class="previous list-inline-item">
                                            <a href="{% url 'message:index' %}">
                                                <button type="button" class="ladda-button btn btn-info"
                                                    data-style="slide-right"><i class="mdi mdi-backspace-outline"></i>
                                                    Back
                                                </button>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div> 
                    </div> 
                </div>
            </div>
        </div> 
    </div> 

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

templates/message/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Edit Message</h4>
                            <div class="row">
                                <div class="col-lg-12">
                                    <form method="post" action="{% url 'message:update' message.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" id="id" name="id" value="{{ message.id }}">
                                        <div class="form-group row">
                                            <label for="inputMessage" class="col-4 col-form-label">NIM</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ message.nim }}" name="nim"
                                                    class="form-control parsley-success"
                                                    placeholder="Silahkan Masukan NIM" data-parsley-id="40">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputMessage" class="col-4 col-form-label">Nama</label>
                                            <div class="col-7">
                                                <input type="text" value="{{ message.name }}" name="name"
                                                    class="form-control parsley-success"
                                                    placeholder="Silahkan Masukan Nama" data-parsley-id="40">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="inputMessage" class="col-4 col-form-label">Pesan</label>
                                            <div class="col-7">
                                                <textarea name="word" class="form-control parsley-success"
                                                    placeholder="Silahkan Masukan Pesan"
                                                    data-parsley-id="40">{{ message.word }}</textarea>
                                            </div>
                                        </div>
                                        <ul class="list-inline wizard mt-3">
                                            <li class="previous list-inline-item">
                                                <a href="{% url 'message:index' %}">
                                                    <button type="button" class="ladda-button btn btn-info"
                                                        data-style="slide-right"><i
                                                            class="mdi mdi-backspace-outline"></i> Back
                                                    </button>
                                                </a>
                                            </li>
                                            <li class="next list-inline-item">
                                                <button type="button" class="btn btn-success waves-effect waves-light"
                                                    data-toggle="modal" data-style="slide-right"
                                                    data-target=".bs-example-modal-center{{file.id}}"><i
                                                        class="mdi mdi-content-save-outline mr-1"></i> Save</button>

                                                <div class="modal fade bs-example-modal-center{{file.id}}" tabindex="-1"
                                                    role="dialog" aria-labelledby="myCenterModalLabel"
                                                    aria-hidden="true" style="display: none;">
                                                    <div class="modal-dialog modal-dialog-centered">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title" id="myCenterModalLabel">Are you
                                                                    sure
                                                                    to save?</h4>
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                    aria-hidden="true">×</button>
                                                            </div>

                                                            <div class="modal-footer">
                                                                <button type="button"
                                                                    class="btn btn-secondary waves-effect"
                                                                    data-dismiss="modal">Close</button>
                                                                <button type="submit"
                                                                    class="btn btn-success waves-effect waves-light"
                                                                    data-style="slide-right"><i
                                                                        class="mdi mdi-content-save-outline mr-1"></i>
                                                                    Save</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </form>
                                </div> 
                            </div>
                        </div> 
                    </div> 
                </div>
            </div>
        </div> 
    </div> <

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

templates/message/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<!-- Footable css -->
<link href="{% static 'libs/footable/footable.core.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">
            {% include "base_page_title.html" %}
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Message List</h4><br>
                            <a href="{% url 'message:create' %}">
                                <button type="button" class="btn btn-success">Create</button>
                            </a>
                            <p></p>
                            <table id="state-saving-datatable" class="table activate-select dt-responsive nowrap">
                                <thead>
                                    <tr>
                                        <th>NIM</th>
                                        <th>Full Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if messages %}
                                    {% for message in messages %}
                                    <tr>
                                        <th>{{ message.nim }}</th>
                                        <th>{{ message.name }}</th>
                                        <td>
                                            <a href="{% url 'message:edit' message.id %}">
                                                <button type="button" class="ladda-button btn btn-info"
                                                    data-style="slide-right"><i class="mdi mdi-square-edit-outline"></i>
                                                    Edit
                                                </button>
                                            </a>
                                            <a href="{% url 'message:detail' message.id %}">
                                                <button type="button" class="ladda-button btn btn-primary"
                                                    data-style="slide-right"><i
                                                        class="mdi mdi-alert-circle-outline"></i>
                                                    Detail
                                                </button>
                                            </a>

                                            <button type="button" class="btn btn-danger waves-effect waves-light"
                                                data-toggle="modal" data-target=".bs-example-modal-center{{file.id}}"><i
                                                    class="mdi mdi-delete"></i> Delete</button>

                                            <div class="modal fade bs-example-modal-center{{file.id}}" tabindex="-1"
                                                role="dialog" aria-labelledby="myCenterModalLabel" aria-hidden="true"
                                                style="display: none;">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title" id="myCenterModalLabel">Are you sure
                                                                to delete?</h4>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                aria-hidden="true">×</button>
                                                        </div>

                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary waves-effect"
                                                                data-dismiss="modal">Close</button>
                                                            <a href="{% url 'message:delete' message.id %}">
                                                                <button type="button"
                                                                    class="btn btn-danger waves-effect waves-light"
                                                                    data-style="slide-right"><i
                                                                        class="mdi mdi-delete"></i> Delete</button>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td colspan="5">Data tidak ditemukan.</td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}