audio/urls.py
from django.urls import path

from . import views

app_name = 'audio'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:id>/edit/', views.edit, name='edit'),
    # path('<int:id>/update/', views.update, name='update'),
    # path('<int:id>/save/', views.save, name='save'),
    # path('<int:id>/delete/', views.delete, name='delete'),

    # path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('save/', views.save, name='save'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/process/', views.process, name='process'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

grade/urls.py
from django.urls import path

from . import views

app_name = 'grade'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/process/', views.process, name='process'),
]

message/urls.py
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('store/', views.store, name='store'),
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

speechclassification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard'), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('grade/', include('grade.urls')),
    path('audio/', include('audio.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('tugas_2/', include('tugas_2.urls')),
    path('message/', include('message.urls')),
    path('message/', include('message.urls')),
    path('workplace_user_network/', include('workplace_user_network.urls')),
    
    path('api/', include('snippets_api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tugas_2/urls.py
from django.urls import path

from . import views

app_name = 'tugas_2'

urlpatterns = [
    path('', views.index, name='index'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Speech Classification</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% include "base_css.html" %}
    
    {% block css %}{% endblock %}

</head>

<body>

    <!-- Begin page -->
    <div id="wrapper">

        {% include "base_topbar.html" %}

        {% include "base_sidebar_left.html" %}

        {% block content %}{% endblock %}


    </div>
    <!-- END wrapper -->

    {% include "base_sidebar_right.html" %}

    {% include "base_js.html" %}

    {% block js %}{% endblock %}

</body>

</html>

templates/base_content.html
{% load static %}
{% extends 'audio/base_index.html' %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "audio/base_page_title.html" %}

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">File List</h4>
                            <p></p>
                            <table id="state-saving-datatable" class="table activate-select dt-responsive nowrap">
                                <thead>
                                    <tr>
                                        <th>Upload Date</th>
                                        <th>Aplicant Name</th>
                                        <th>File Name</th>
                                        <!--<th>Edit</th>-->
                                        <th>Process</th>
                                        <!--<th>Full Text</th>-->
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for text in data2 %}
                                    <tr>
                                        <td>{{text.upload_date}}</td>
                                        <td>{{text.aplicants_name}}</td>
                                        <td>{{text.title}}</td>
                                        <!--<td>
                                                        <a href="speech-to-text-edit.html">
                                                        <button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i>
                                                        </button>
                                                      </a></td>-->
                                        <td>
                                            <a href="{% url 'speech_to_text_process' text.id %}">
                                                <button type="button" class="ladda-button btn btn-info"
                                                    data-style="slide-right"><i class="mdi mdi-send"></i></button>
                                            </a>
                                        </td>
                                        <!--<td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed neque vel massa molestie tempus at in eros. Ut sed augue ac ante bibendum efficitur ac eget lectus. In vulputate justo nec mollis gravida. Aliquam tristique tincidunt elementum. Maecenas cursus mauris sit amet rhoncus semper. Suspendisse a augue at eros eleifend consequat nec volutpat purus. Aenean viverra viverra est sed sodales. Donec porta enim quis sem lacinia, ac ullamcorper tortor sodales. Maecenas pharetra tincidunt augue non varius. Nunc euismod ut ipsum quis porta. Sed tristique eros sed urna dictum, varius ultricies nulla vehicula. In posuere lectus nec mollis ultricies. Morbi semper ligula ac nibh tempor auctor. Ut varius posuere mi, ut dapibus ipsum cursus non. Aliquam non sapien sed nulla elementum suscipit ac ut nisi.</td>-->
                                    </tr>
                                    {% endfor %}
                                    <!--<tr>
                                                        <td>Mark Jurcas</td>
                                                        <td>Senior Marketing Designer</td>
                                                        <td>London</td>
                                                        <td>43</td>
                                                        <td>2012/12/18</td>
                                                        <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                                        <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                                    </tr>
                                                    <tr>
                                                        <td>Jacob Bima</td>
                                                        <td>Regional Director</td>
                                                        <td>London</td>
                                                        <td>19</td>
                                                        <td>2010/03/17</td>
                                                        <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                                        <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                                    </tr>
                                                    <tr>
                                                        <td>Larry the Bird</td>
                                                        <td>Marketing Designer</td>
                                                        <td>London</td>
                                                        <td>66</td>
                                                        <td>2012/11/27</td>
                                                        <td><a href="speech-to-text-edit.html"><button type="button" class="ladda-button btn btn-success" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                                        <td><a href="detail-data.html"><button type="button" class="ladda-button btn btn-info" data-style="slide-right"><i class="mdi mdi-send"></i></button></a></td>
                                                    </tr>-->
                                </tbody>
                            </table>

                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div>
            <!-- end row-->

        </div> <!-- container -->

    </div> <!-- content -->

    {% include "audio/base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

templates/base_css.html
{% load static %}

<!-- App css -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" />

<!-- Loading button css -->
<link href="{% static 'libs/ladda/ladda-themeless.min.css' %}" rel="stylesheet" type="text/css" />

templates/base_footer.html
{% load static %}

<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2019 &copy; Speech Classification by <a href="https://telkomuniversity.ac.id">Telkom Univeristy</a>
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="javascript:void(0);">About Us</a>
                    <a href="javascript:void(0);">Help</a>
                    <a href="javascript:void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

templates/base_js.html
{% load static %}

<!-- Vendor js -->
<script src="{% static 'js/vendor.min.js' %}"></script>

<!-- Loading buttons js -->
<script src="{% static 'libs/ladda/spin.js' %}"></script>
<script src="{% static 'libs/ladda/ladda.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/app.min.js' %}"></script>

<!-- Table Editable plugin-->
<!-- <script src="{% static 'libs/jquery-tabledit/jquery.tabledit.min.js' %}"></script> -->

<!-- Table editable init-->
<!-- <script src="{% static 'js/pages/tabledit.init.js' %}"></script> -->

<!-- Buttons init js-->
<!-- <script src="{% static 'js/pages/loading-btn.init.js' %}"></script> -->

templates/base_page_title.html
{% load static %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item active">Speech Classification</li>
                </ol>
            </div>
            <h4 class="page-title">Speech Classification</h4>
        </div>
    </div>
</div>
<!-- end page title -->

templates/base_sidebar.html
{% load static %}

<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <div class="slimscroll-menu">

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul class="metismenu" id="side-menu">

                <li class="menu-title">Navigation</li>

                <li>
                    <a href="index.html">
                        <i class="fe-airplay"></i>
                        <!--<span class="badge badge-success badge-pill float-right">4</span>-->
                        <span> Dashboard </span>
                    </a>
                </li>

                <li>
                    <a href="audio-upload.html">
                        <i class="far fa-file-audio"></i>
                        <span> Audio Upload </span>
                        <!--<span class="menu-arrow"></span>-->
                    </a>
                    <!--<ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="apps-kanbanboard.html">Kanban Board</a>
                                </li>
                                <li>
                                    <a href="apps-calendar.html">Calendar</a>
                                </li>
                                <li>
                                    <a href="apps-contacts.html">Contacts</a>
                                </li>
                                <li>
                                    <a href="apps-projects.html">Projects</a>
                                </li>
                                <li>
                                    <a href="apps-tickets.html">Tickets</a>
                                </li>
                                <li>
                                    <a href="apps-companies.html">Companies</a>
                                </li>
                            </ul>-->
                </li>

                <li>
                    <a href="speech-to-text.html">
                        <i class="fe-users"></i>
                        <span> Speech to Text </span>
                    </a>
                </li>

                <li>
                    <a href="text-grading.html">
                        <i class="fas fa-envelope-open-text"></i>
                        <span> Text Grading </span>
                    </a>
                </li>

            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

templates/base_sidebar_left.html
{% load static %}

<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <div class="slimscroll-menu">

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul class="metismenu" id="side-menu">

                <li class="menu-title">Navigation</li>

                <li>
                    <a href="{% url 'dashboard:index' %}">
                        <i class="fe-airplay"></i>
                        <!--<span class="badge badge-success badge-pill float-right">4</span>-->
                        <span> Dashboard </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'audio:index' %}">
                        <i class="far fa-file-audio"></i>
                        <span> Audio Upload </span>
                        <!--<span class="menu-arrow"></span>-->
                    </a>
                    <!--<ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="apps-kanbanboard.html">Kanban Board</a>
                                </li>
                                <li>
                                    <a href="apps-calendar.html">Calendar</a>
                                </li>
                                <li>
                                    <a href="apps-contacts.html">Contacts</a>
                                </li>
                                <li>
                                    <a href="apps-projects.html">Projects</a>
                                </li>
                                <li>
                                    <a href="apps-tickets.html">Tickets</a>
                                </li>
                                <li>
                                    <a href="apps-companies.html">Companies</a>
                                </li>
                            </ul>-->
                </li>

                <li>
                    <a href="{% url 'transcribe:index' %}">
                        <i class="fe-users"></i>
                        <span> Speech to Text </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'grade:index' %}">
                        <i class="fas fa-envelope-open-text"></i>
                        <span> Text Grading </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'tugas_2:index' %}">
                        <i class="dripicons-bookmark"></i>
                        <span> Tugas 2 </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'message:index' %}">
                        <i class="dripicons-message"></i>
                        <span> Message </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'workplace_user_network:index' %}">
                        <i class=""></i>
                        <span style="font-size: 14px;">Workplace User Network</span>
                    </a>
                </li>

            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

templates/base_sidebar_right.html
{% load static %}

<!-- Right Sidebar -->
<div class="right-bar">
    <div class="rightbar-title">
        <a href="javascript:void(0);" class="right-bar-toggle float-right">
            <i class="dripicons-cross noti-icon"></i>
        </a>
        <h5 class="m-0 text-white">Settings</h5>
    </div>
    <div class="slimscroll-menu">
        <!-- User box -->
        <div class="user-box">
            <div class="user-img">
                <img src="{% static 'images/users/user-3.jpg' %}" alt="user-img" title="Mat Helme"
                    class="rounded-circle img-fluid">
                <a href="javascript:void(0);" class="user-edit"><i class="mdi mdi-pencil"></i></a>
            </div>

            <h5><a href="javascript: void(0);">Donni Richasdy</a> </h5>
            <p class="text-muted mb-0"><small>Admin Head</small></p>
        </div>

        <!-- Settings -->
        <hr class="mt-0" />
        <h5 class="pl-3">Basic Settings</h5>
        <hr class="mb-0" />

        <div class="p-3">
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox1" type="checkbox" checked>
                <label for="Rcheckbox1">
                    Notifications
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox2" type="checkbox" checked>
                <label for="Rcheckbox2">
                    API Access
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox3" type="checkbox">
                <label for="Rcheckbox3">
                    Auto Updates
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-2">
                <input id="Rcheckbox4" type="checkbox" checked>
                <label for="Rcheckbox4">
                    Online Status
                </label>
            </div>
            <div class="checkbox checkbox-primary mb-0">
                <input id="Rcheckbox5" type="checkbox" checked>
                <label for="Rcheckbox5">
                    Auto Payout
                </label>
            </div>
        </div>

        <!-- Timeline -->
        <hr class="mt-0" />
        <h5 class="pl-3 pr-3">Messages <span class="float-right badge badge-pill badge-danger">25</span></h5>
        <hr class="mb-0" />
        <div class="p-3">
            <div class="inbox-widget">
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="{% static 'images/users/user-2.jpg' %}" class="rounded-circle"
                            alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Tomaslau</a></p>
                    <p class="inbox-item-text">I've finished it! See you so...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="{% static 'images/users/user-3.jpg' %}" class="rounded-circle"
                            alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Stillnotdavid</a>
                    </p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="{% static 'images/users/user-4.jpg' %}" class="rounded-circle"
                            alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Kurafire</a></p>
                    <p class="inbox-item-text">Nice to meet you</p>
                </div>

                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="{% static 'images/users/user-5.jpg' %}" class="rounded-circle"
                            alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Shahedk</a></p>
                    <p class="inbox-item-text">Hey! there I'm available...</p>
                </div>
                <div class="inbox-item">
                    <div class="inbox-item-img"><img src="{% static 'images/users/user-6.jpg' %}" class="rounded-circle"
                            alt=""></div>
                    <p class="inbox-item-author"><a href="javascript: void(0);" class="text-light">Adhamdannaway</a>
                    </p>
                    <p class="inbox-item-text">This theme is awesome!</p>
                </div>
            </div> <!-- end inbox-widget -->
        </div> <!-- end .p-3-->

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

templates/base_topbar.html
{% load static %}

<!-- Topbar Start -->
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">

        <li class="d-none d-sm-block">
            <form class="app-search">
                <div class="app-search-box">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search...">
                        <div class="input-group-append">
                            <button class="btn" type="submit">
                                <i class="fe-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </li>

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#"
                role="button" aria-haspopup="false" aria-expanded="false">
                <img src="{% static 'images/users/user-3.jpg' %}" alt="user-image" class="rounded-circle">
                <span class="pro-user-name ml-1">
                    Donni <i class="mdi mdi-chevron-down"></i>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="fe-user"></i>
                    <span>My Account</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="fe-settings"></i>
                    <span>Settings</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="fe-lock"></i>
                    <span>Lock Screen</span>
                </a>

                <div class="dropdown-divider"></div>

                <!-- item-->
                <a href="pages-login.html" class="dropdown-item notify-item">
                    <i class="fe-log-out"></i>
                    <span>Logout</span>
                </a>

            </div>
        </li>

        <li class="dropdown notification-list">
            <a href="javascript:void(0);" class="nav-link right-bar-toggle waves-effect waves-light">
                <i class="fe-settings noti-icon"></i>
            </a>
        </li>


    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a href="index.html" class="logo text-center">
            <span class="logo-lg" style="font-size: 15px; line-height: 20px; padding: 20px; font-weight: bold">
                SISTEM SELEKSI <br>PELAMAR KERJA
                <!-- <span class="logo-lg-text-light">UBold</span> -->
            </span>
            <span class="logo-sm" style="font-size: 15px; font-weight: bold;">
                <!-- <span class="logo-sm-text-dark">U</span> -->
                SSPK
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li>
            <button class="button-menu-mobile waves-effect waves-light">
                <i class="fe-menu"></i>
            </button>
        </li>

    </ul>
</div>
<!-- end Topbar -->