audio/urls.py
from django.urls import path

from . import views

app_name = 'audio'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:id>/edit/', views.edit, name='edit'),
    # path('<int:id>/update/', views.update, name='update'),
    # path('<int:id>/save/', views.save, name='save'),
    # path('<int:id>/delete/', views.delete, name='delete'),

    # path('', views.IndexView.as_view(), name='index'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    path('save/', views.save, name='save'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/process/', views.process, name='process'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

speechclassification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard'), name='home'),
    path('dashboard/', include('dashboard.urls')),
    path('grade/', include('grade.urls')),
    path('audio/', include('audio.urls')),
    path('transcribe/', include('transcribe.urls')),
    path('tugas_2/', include('tugas_2.urls')),
    path('message/', include('message.urls')),
    path('message/', include('message.urls')),
    path('workplace_user_network/', include('workplace_user_network.urls')),
    
    path('api/', include('snippets_api.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

from django.http import HttpResponse
from grade.models import Grade
from audio.models import File
from transcribe.models import Transcribe

def index(request):
    # return HttpResponse("Hello, world. You're at the dashboard index.")
    target_count = 100

    file_count = File.objects.count()
    file_percent = file_count/target_count*100

    transcribe_count = Transcribe.objects.count()
    transcribe_percent = transcribe_count/target_count*100

    grade_count = Grade.objects.count()
    grade_percent = grade_count/target_count*100

    grade_list = Grade.objects.order_by('-total')[:5]
    context = {
        'grade_list':grade_list,

        'file_count':file_count,
        'file_percent':file_percent,

        'transcribe_count':transcribe_count,
        'transcribe_percent':transcribe_percent,
        
        'grade_count':grade_count,
        'grade_percent':grade_percent,
        }
    return render(request, 'dashboard/index.html', context)

templates/dashboard/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<!-- plugin css -->
<link href="{% static 'libs/jquery-vectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            {% include "base_page_title.html" %}

            <div class="row">
                <div class="col-md-6 col-xl-4">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-6">
                                <div class="avatar-sm bg-blue rounded">
                                    <i class="fe-mic avatar-title font-22 text-white"></i>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="text-right">
                                    <h3 class="my-1"><span data-plugin="counterup">{{ file_count }}</span></h3>
                                    <p class="text-muted mb-1 text-truncate">Audio</p>
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <h6 class="text-uppercase">Target <span class="float-right">{{ file_percent }}%</span></h6>
                            <div class="progress progress-sm m-0">
                                <div class="progress-bar bg-blue" role="progressbar" aria-valuenow="{{ file_count }}"
                                    aria-valuemin="0" aria-valuemax="100" style="width: {{ file_percent }}%">
                                    <span class="sr-only">60% Complete</span>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end card-box-->
                </div> <!-- end col -->

                <div class="col-md-6 col-xl-4">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-6">
                                <div class="avatar-sm bg-success rounded">
                                    <i class="fe-file-text avatar-title font-22 text-white"></i>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="text-right">
                                    <h3 class="my-1"><span data-plugin="counterup">{{ transcribe_count }}</span></h3>
                                    <p class="text-muted mb-1 text-truncate">Transcription</p>
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <h6 class="text-uppercase">Target <span class="float-right">{{ transcribe_percent }}%</span></h6>
                            <div class="progress progress-sm m-0">
                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="{{ transcribe_count }}"
                                    aria-valuemin="0" aria-valuemax="100" style="width: {{ transcribe_percent }}%">
                                    <span class="sr-only">49% Complete</span>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end card-box-->
                </div> <!-- end col -->

                <div class="col-md-6 col-xl-4">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-6">
                                <div class="avatar-sm bg-warning rounded">
                                    <i class="fe-thumbs-up avatar-title font-22 text-white"></i>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="text-right">
                                    <h3 class="my-1"><span data-plugin="counterup">{{ grade_count }}</span></h3>
                                    <p class="text-muted mb-1 text-truncate">Grade</p>
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <h6 class="text-uppercase">Target <span class="float-right">{{ grade_percent }}%</span></h6>
                            <div class="progress progress-sm m-0">
                                <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="{{ grade_count }}"
                                    aria-valuemin="0" aria-valuemax="100" style="width: {{ grade_percent }}%">
                                    <span class="sr-only">18% Complete</span>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end card-box-->
                </div> <!-- end col -->

            </div>
            <!-- end row -->

            <div class="row">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-widgets">
                                <a href="javascript: void(0);" data-toggle="reload"><i class="mdi mdi-refresh"></i></a>
                                <a data-toggle="collapse" href="#cardCollpase5" role="button" aria-expanded="false"
                                    aria-controls="cardCollpase5"><i class="mdi mdi-minus"></i></a>
                                <a href="javascript: void(0);" data-toggle="remove"><i class="mdi mdi-close"></i></a>
                            </div>
                            <h4 class="header-title mb-0">Top 5 Grading</h4>

                            <div id="cardCollpase5" class="collapse pt-3 show">
                                <div class="table-responsive">
                                    <table class="table table-hover table-centered mb-0">
                                        <thead>
                                            <tr>
                                                <th>Nama File</th>
                                                <th>Dibuat Pada</th>
                                                <th>Diupdate Pada</th>
                                                <th>Nilai</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            {% for grade in grade_list %}
                                            <tr>
                                                <td>{{ grade.File.name}}</td>
                                                <td>{{ grade.created_at}}</td>
                                                <td>{{ grade.created_at}}</td>
                                                <td>{{ grade.total}}</td>
                                                <td><a href="{% url 'audio:edit' grade.File.id %}">
                                                        <button type="button" class="ladda-button btn btn-success"
                                                            data-style="slide-right"><i class="mdi mdi-square-edit-outline"></i>
                                                            View
                                                        </button>
                                                    </a></td>
                                                
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div> <!-- end table responsive-->
                            </div> <!-- collapsed end -->
                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->

        </div> <!-- container -->

    </div> <!-- content -->

    {% include "base_footer.html" %}

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

{% block js %}

<!-- Plugins js-->
<script src="{% static 'libs/jquery-sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'libs/jquery-vectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'libs/jquery-vectormap/jquery-jvectormap-world-mill-en.js' %}"></script>

<!-- Dashboard 2 init -->
<script src="{% static 'js/pages/dashboard-2.init.js' %}"></script>

{% endblock %}